### PR TITLE
Adding more robustness tests

### PR DESCRIPTION
**Pull request by andrewlee94**
Adds some more robustness tests for core unit models.

### CODE REVIEW

**Review by MarcusHolly — COMMENTED** [review]
A few general questions/comments:

1.) Why are these files going in this new directory as opposed to somewhere like `idaes.core.util`?

2.) It wasn't immediately obvious to me (by the name alone) that requil referred to the equilibrium reactor, altho maybe this is a common abbreviation that I'm just not aware of.

**Comment by andrewlee94** [comment]
@MarcusHolly These go in a completely separate repository (note this is `idaes-compatibilty`, not `idaes-pse`) so that they cannot be easily changed. These tests are intended to be our benchmarks to ensure that performance is consistent across versions of IDAES, and thus we don;t want them somewhere were a developer can change them just because they start failing.

Also, this is not user facing code and not something most users will ever be aware of, thus naming is less of a concern.

**Review by MarcusHolly — APPROVED** [review]
LGTM

**Review by dallan-keylogic — APPROVED** [review]
LGTM

**Pull request merged**
